version: "3"

services:
  postgres:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: skeleton
      POSTGRES_PASSWORD: skeleton
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: skeleton
    volumes:
      - db_data:/var/lib/postgresql/data

  gcs:
    image: fsouza/fake-gcs-server:1.45.2
    ports:
      - "5050:5050"
    command:
      [
        "-scheme",
        "http",
        "-port",
        "5050",
        "-external-url",
        "http://localhost:5050",
        "-backend",
        "memory",
      ]
    volumes:
      - storage_data:/storage

volumes:
  db_data:
  storage_data: