version: "3"

services:
  postgres:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: skeleton
      POSTGRES_PASSWORD: skeleton
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: skeleton
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
